### ISSUE TITLE
`mondo.sssom.tsv`: Orphanet prefix changed to `orphanet.ordo`?

### ISSUE THREAD

**Issue by joeflack4** [monarch-initiative/mondo-ingest#369]
## Overview
I am working on the [synchronization pipeline](https://github.com/monarch-initiative/mondo-ingest/issues/92), and I just updated to the latest `mondo.sssom.tsv`. I noticed things were strange and then saw that the Orphanet prefix has changed from `Orphanet` to `orphanet.ordo`.

Is this temporary / unexpected? Or is this (or a change like this) permanent going forward?

I don't see any new changes to `mondo-ingest` `main` or any new PRs about this, so I would guess that this is going to break a lot of things.

**Comment by matentzn** [comment]
There must be a few issue about this and it has to be fixed with some urgency

**Comment by joeflack4** [comment]
I'm not sure at the moment how to fix it, and I don't see any issues, but if you have no idea and want me to figure out, just let me know.

**Comment by matentzn** [comment]
See here for details: https://github.com/monarch-initiative/mondo-ingest/issues/353

It is supposed to be fixed - if its not, we need to fix it urgently. 

The line of code that needs fixing is https://github.com/monarch-initiative/mondo/blob/cf645299eed2784a20649e208d75661ab2f5d87b/src/ontology/mondo.Makefile#L580

**Comment by joeflack4** [comment]
I took a look at #353. I see that there was a change to `orphanet.ordo` at that time.
This seems related as well; a prior attempt to fix the problem:
- https://github.com/biopragmatics/bioregistry/pull/929

I looked at the line of code you mentioned, but I don't see what is relevant there. There's nothing about `orphanet.ordo` in that goal, or the script and config that it's using.

Also I did a global search for `orphanet.ordo` in both `mondo` and `mondo-ingest`, and nothing came up (except for inside of `mondo.sssom.tsv` and some commented out lines in lexmatch.

**Comment by matentzn** [comment]
The problem is not obvious but needs testing and trying. The line i send uses SSSOM python lib under the hood which in turn uses "curies" module with a default curie map, which defaults to bioregistry using that prefix. I didn't keep track of what was fixed where, needs testing.

**Comment by joeflack4** [comment]
This is still an issue, right?

I've hard-coded a fix in the synchronization (subclass) pipeline, but until fixed I think this kind of patch needs to be elsewhere:

https://github.com/monarch-initiative/mondo-ingest/blob/1f07896f6a51f4289f903ef41d7d52be8323fd77/src/scripts/sync_subclassof.py#L274-L275

**Comment by matentzn** [comment]
No, this has been fixed about a week ago!

**Comment by joeflack4** [comment]
Ok, that's good. Closing this then.
